apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-entrypoint
data:
  entrypoint.sh: |
    #!/bin/sh
    git clone https://github.com/huynhdnguyen/ansible.git /app/repo
    cd /app/repo
    ansible-playbook your-playbook.yml

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ansible-runner-job
spec:
  ttlSecondsAfterFinished: 100  # Job sẽ được xóa sau 100 giây sau khi hoàn thành
  template:
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'chmod +x /app/entrypoint.sh']
        volumeMounts:
        - name: entrypoint-script
          mountPath: /app/entrypoint.sh
          subPath: entrypoint.sh
      containers:
      - name: ansible-runner
        image: cytopia/ansible:latest
        command: ["/bin/sh", "-c", "/app/entrypoint.sh"]
        volumeMounts:
        - name: entrypoint-script
          mountPath: /app/entrypoint.sh
          subPath: entrypoint.sh
          readOnly: true
        env:
        - name: GIT_SSH_COMMAND
          value: "ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no"
      restartPolicy: Never
      volumes:
      - name: entrypoint-script
        configMap:
          name: ansible-entrypoint
  backoffLimit: 0  # Đảm bảo Job không được khởi động lại nếu thất bại
