apiVersion: v1
kind: ConfigMap
metadata:
  name: ansible-entrypoint
data:
  entrypoint.sh: |
    #!/bin/sh
    git clone https://github.com/huynhdnguyen/ansible.git /app/repo
    cd /app/repo
    ansible-playbook your-playbook.yml

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ansible-runner-job
spec:
  template:
    spec:
      containers:
      - name: ansible-runner
        image: willhallonline/ansible:latest  # Sử dụng image willhallonline/ansible
        command: ["/bin/sh", "-c", "cp /scripts/entrypoint.sh /tmp/entrypoint.sh && chmod +x /tmp/entrypoint.sh && /tmp/entrypoint.sh"]
        volumeMounts:
        - name: entrypoint-script
          mountPath: /scripts/entrypoint.sh
          subPath: entrypoint.sh
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: entrypoint-script
        configMap:
          name: ansible-entrypoint
  backoffLimit: 0  # Đảm bảo Job không được khởi động lại nếu thất bại
